services:
  - type: web
    name: project-union
    runtime: php
    plan: free
    buildCommand: "composer install --no-dev && npm install && npm run build && php artisan key:generate --force && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: laravel-db # POZOR: Změňte na přesný název vaší databáze na Renderu
          property: internalConnectionString
      - key: APP_KEY # Důležité: APP_KEY je potřeba nastavit ručně
        sync: false

databases:
  - name: laravel-db # POZOR: Změňte na přesný název vaší databáze na Renderu
    plan: free