services:
  - type: web
    name: project-union
    runtime: docker
    plan: free
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: project-union-db # Zkontrolujte název databáze
          property: connectionString
      - key: APP_URL # Tuto proměnnou nastavíme ručně
        sync: false
      - key: APP_KEY # Tuto proměnnou nastavíme ručně
        sync: false
      - key: LOG_CHANNEL
        value: stderr

databases:
  - name: project-union-db # Zkontrolujte název databáze
    plan: free